### PR TITLE
Fix bug that displays invalid date

### PR DESCRIPTION
**Pull request by hermancaldara**
Some refactor modified the function "lastRun" to use another library than Moment.js to handle date and that gives the "Last updated at Invalid Date" message. Fix the bug only passing the correctarameters to the new library.

Remotion of "index" parameters is just to lint code.

### CODE REVIEW

**Comment by ggarnier** [comment]
Shouldn't we also remove `moment` from `package.json`?

**Comment by hermancaldara** [comment]
Doing this now, @ggarnier!

**Comment by hermancaldara** [comment]
> Shouldn't we also remove `moment` from `package.json`?

Done!

**Comment by gvarandas** [comment]
Oooops, my bad on that one 😅

**Comment by hermancaldara** [comment]
No problem, @gvarandas! 😉

**Pull request merged**
