### PR TITLE
[Proposal] Adding NPM + Webpack Integration

### PR DESCRIPTION
**Pull request by gvarandas**
# Feature Proposal
Realized that the project does not rely on NPM to manage its dependencies (which might be due to its creation a long ago).
This led to a proposal of integrating NPM dependency management along with a bundler to deliver assets using modern tooling (like ES6+ JavaScript).

# Pros
- [x] More concise architecture, adherent with other libraries;
- [x] Allows dependency version control without new deploys (using SEMVER);
- [x] Allow the use of modern JavaScript features (like ES6+ syntax) through BabelJS;
- [x] Allow future integration of automated tooling like parsing SASS/LESS, optimizing assets (css, images);
- [x] Allow bundling optimizations, like minification, tree shaking, bundle split.

# Cons
This integration proposal require an additional build step, to generate the assets in the `dist` folder, which I'm not sure that is supported by the current project objectives (downloading and deploying as is).
This could be avoided by checking in the `dist` folder, with the already parsed assets and injecting `index.html` directly with the result of them (although this would possibly mangle the dinamicity of the bundling process).

# Bonus
- [x] ESLint integration comes as a plus;
- [x] Substituted `momentJS` for `date-fns`, which allows tree shaking and a reduced bundle size.

I'm all for feedbacks and would be really glad to contribute to this project, as we're currently thinking about using it in our Gitlab hosting. 🤖

### CODE REVIEW

**Comment by ggarnier** [comment]
This change does bring a couple of advantages, besides helping us to add tests. On the other side, I don't like the idea of adding too much complexity to a project that was conceived to be simple.

But I think the boilerplate code you added is not that large (compared to others I've seen around). I think we can go for it.

Can you fix the conflicts in `index.html`?

**Comment by gvarandas** [comment]
@ggarnier sure do. Will make sure to handle this in the weekend.

**Comment by gvarandas** [comment]
Done 🤖

**Comment by ggarnier** [comment]
@gvarandas I think I just made a mess. I manually merged your commits, but now I can't mark the PR as merged...

**Comment by gvarandas** [comment]
@ggarnier cant you edit the master branch head using a rebase and merge this PR on top of it? It should be enough (the rebase could delete the top commit, which is the merge).

**Comment by ggarnier** [comment]
Done! Thanks for your contribution!

**Pull request merged**
