### PR TITLE
[Feature] Adding tests support

### PR DESCRIPTION
**Pull request by gvarandas**
# Feature
- [x] Added `Jest` testing library (and other support ones);
- [x] Configured the environment to support testing features;
- [x] Added sample tests to guarantee critical functionalities (needs future improvements);
- [x] Added mock files to simplify tests;

# Steps to run the tests on this branch
* Checkout the branch
* `npm install`
* `npm test`

This solves #4.

---

[Jest Docs](https://jestjs.io/docs/en/getting-started)

⚠️ It is important to disclaim that increasing further testability, it is necessary to refactor the application to reduce method _side effects_. That should secure more stability to every step of the assertion, although, due to the size of this change, it might be a good idea to submit a separate PR to attack that.

### CODE REVIEW

**Comment by ggarnier** [comment]
@gvarandas I'm getting errors in the snapshotting test:

```
    @@ -40,19 +40,69 @@
        "$root": [Circular],
        "_context": undefined,
        "_data": Object {
          "gitlab": "gitlab.test.com",
          "invalidConfig": false,
    -     "lastRun": "2018-10-01 - 00:00:00",
    +     "lastRun": "2018-10-01 - 03:00:00",
          "loading": false,
          "onError": null,
          "orderFields": Object {
            "dir": "asc",
            "field": "project",
          },
    -     "pipelines": Array [],
    -     "pipelinesMap": Object {},
    +     "pipelines": Array [
    +       Object {
    +         "author": "Guilherme Varandas",
    +         "branch": "branch1",
    +         "id": 23827851,
    +         "project": "project1",
    +         "project_path": "namespace/project1",
 ...
```

The `LastRun` field could be fixed setting the timezone (I tested in a container without timezone configuration set). But even after fixing this, I got the errors in `pipelines` and `pipelinesMap` fields.

**Comment by gvarandas** [comment]
@ggarnier just updated the branch with the timezone fix. Could you test it again, please?

**Comment by ggarnier** [comment]
@gvarandas timezone issue is fixed. Now I only get that error with `pipelines` and `pipelinesMap` fields.

**Comment by gvarandas** [comment]
Can you describe the steps to reproduce the error? I can't seem to identify the probable cause. 😞

**Comment by ggarnier** [comment]
I was running it inside a Docker container, using `node:10.3.0` image. But I just tested with other versions, and it works with node >= 10.4.0.

**Pull request merged**
